std_msgs/Bool use_friction
std_msgs/Float32 f_s      # Static (stiction) friction torque [Nm]
std_msgs/Float32 f_c      # Coulomb (dynamic) friction torque [Nm]
std_msgs/Float32 sigma0   # Stiffness coefficient [Nm/rad]
std_msgs/Float32 sigma1   # Damping coefficient [Nm·s/rad]
std_msgs/Float32 sigma2   # Viscous friction coefficient [Nm·s/rad]
std_msgs/Float32 alpha    # Transition parameter [s/rad]